### ISSUE TITLE
check-tag-in-branch.yml に関するWikiを修正する

### ISSUE THREAD

**Issue by MarikoMorimoto** [tarosky/workflows#63]
https://github.com/tarosky/workflows/wiki#%E3%82%BF%E3%82%B0%E3%82%92%E3%83%96%E3%83%A9%E3%83%B3%E3%83%81%E3%81%AB%E9%99%90%E5%AE%9A%E3%81%99%E3%82%8B

↑これ
編集権限がなかったので、ご確認と修正をお願いします。

## 修正点

uses: のところ
（誤）`check-tag-in-branch`
（正）`check-tag-in-branch.yml@main`

needs: のところ
（誤）`tag-check`
（正）`tags-check`

### 修正前

```
jobs:
  # タグ付きコミットなら、それがmainブランチにあるのかチェックする
  tags-check:
    uses: tarosky/workflows/.github/workflows/check-tag-in-branch
    if: contains(github.ref, 'refs/tags/')
    with:
      allowed_branch: "main"
  # リリース作業のジョブ
  release:
    needs: tag-check # mainブランチのタグだけで実行
    environment:
      name: production
      url: https://example.com
    steps:
      # 以下、リリース作業のステップ      
```

### 修正後

```
jobs:
  # タグ付きコミットなら、それがmainブランチにあるのかチェックする
  tags-check:
    uses: tarosky/workflows/.github/workflows/check-tag-in-branch.yml@main
    if: contains(github.ref, 'refs/tags/')
    with:
      allowed_branch: "main"
  # リリース作業のジョブ
  release:
    needs: tags-check # mainブランチのタグだけで実行
    environment:
      name: production
      url: https://example.com
    steps:
      # 以下、リリース作業のステップ      
```
